spring:
  application:
    name: NJUPT-competitionManagement

  datasource:
    url: jdbc:mysql://localhost:3306/competitionManagement
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-handlers-package: cn.edu.njupt.handler
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    org.apache.ibatis: INFO

